export enum INVOICE_STATUS {
  ST_SUBMITTED = 'STS',
  ST_REJECTED = 'STR',
  ST_GENERATED = 'STG',
  SN_VALIDATED = 'SNV',
  SN_SHARED = 'SNS',
  SN_ENTITY_CHECKED = 'SNC',
  IVT_HOLD = 'IVTH',
  IVT_REJECTED = 'IVTR',
  PAID = 'P',
}
