export enum INVOICE_TYPE {
  INVOICE = 'INV',
  CERTIFIED_ABSTRUCT_IN_STANDARD_FORMAT = 'CASF',
  FIM_RECONCILLIATION_STATEMENT = 'FRS',
  E_WAY_BILL = 'EWB',
  DELIVERY_CHALLAN = 'DC',
  LR = 'LR',
  LATEST_APPROVED_DEAL_SLIP = 'LADS',
  OTHERS = 'OTHER',
  ABSTRUCT_IN_STANDARD_FORMAT = 'ASF',
  RA_ABSTRUCT = 'RA',
}
